### ISSUE TITLE
Hi, My Name is...

### ISSUE THREAD

**Issue by maxboeck** [maxboeck/webring#1]
Since "Webring" seems to be a trademarked term, we need another name!

I think it would be nice to let the community come up with ideas.
Here are a few first ideas of mine to get the ball rolling (in no particular order):

- Hudddle (with 3 d's)
- Link Loop
- Site Hoop

All ideas welcome!

**Comment by Ansimorph** [comment]
Ad hoc:
Linked List
Web Set
Huddddle (with 4 d's)

**Comment by ste-vg** [comment]
- Web Bevy
- Link Lot
- Site Set
- Hudddddle (with 5 d's)

**Comment by maxboeck** [comment]
@ste-vg I see a pattern here.

maybe we do the google thing and it has as many d's as there are members 😂

**Comment by matuzo** [comment]
Web Hudddles –  I dig it.

**Comment by danfarrow** [comment]
wwwring

**Comment by bridgestew** [comment]
Contiguity

**Comment by gerwitz** [comment]
I think it's important to keep "ring" for the throwback.

First choice: Webring ([Sosumi](https://en.wikipedia.org/wiki/Sosumi)!)

Second choice: IndieRing

**Comment by danfarrow** [comment]
@gerwitz +1 for IndieRing

**Comment by WorldMaker** [comment]
The US trademark for "Webring" was granted in 2007, almost a decade *after* the term was used as generic term by a whole lot of websites. It doesn't seem enforceable to me as even a brief trawl through archive.org should find all sorts of prior use of the term in a generic fashion. It seems almost funny to me that they even bothered to register it as a trademark in 2007. But I'm not a lawyer.

**Comment by weseldridge** [comment]
I also like keeping the ring idea. 

**Ringlet**

**Comment by maxboeck** [comment]
I agree that keeping *ring* in the name is good to keep the connection to the 90s original. 

IndieRing is nice! There's an official IndieWeb Webring though, might be a bit confusing.

**Comment by davmillar** [comment]
Interknot

**Comment by davmillar** [comment]
ClickClique

**Comment by Pneumaticat** [comment]
Portkey ring!

**Comment by wallynm** [comment]
Gnirbew - webring backwards

**Comment by neuroradiology** [comment]
net loop
internet loop
internet ring
web loop
web circle
net circle
web circuit
net circuit

**Comment by simon-brooke** [comment]
How about `toppic`. It has nothing to do with rings, but a ring is typically as collection of websites on a given *topic*, and members of a ring are, hopefully, the *top picks* on that topic.

**Comment by sianglim** [comment]
Hypercircle or HyperRing?

**Comment by daveloyall** [comment]
Some options:

* max-webring
* webring.js
* node-webring (Is your project a Node thing?  I looked at your repo twice and I still don't know.  Not my area.)

Imagine trying to explain to an experienced internet user what your project does without using the word webring.

I did some searching and determined that there were some efforts to make commercial webrings and some of them had 'webring' in the name.  Obviously none of them were very successful.

As far as I know, all the webrings that I interacted with were stand-alone CGI programs.  `webring.pl`, that kind of thing.  Putting some string of your choosing in front of or behind the word webring would be inline with tradition--both for the standalone scripts of yesteryear and the commercial webrings I read about today.

**Comment by daveloyall** [comment]
...A good contender "webring-kit" may have been overlooked on [April 14](https://mxb.dev/blog/webring-kit/). ;)

**Comment by maxboeck** [comment]
Thank you all for your input!

as far as I understand, the issue has been with the term "webring", as that is the tm'd name from 2007. so names containing that are maybe problematic. but then again, as @WorldMaker stated above, webrings have been around far longer than that, and I also have my doubts about the enforceability of that trademark.

Ideally, I'd like to stick with "**Webring**". 
If that's really impossible, my current top choice is "**IndieRing**" (HT @gerwitz)

For now, I'm closing this thread. Thanks again!

**Comment by dar5hak** [comment]
Late comer, but if Webring doesn't work, Sitering? Quite obvious, but without violating the trademark.

**Comment by LautaroLobo12** [comment]
Hm, it's a great idea to bring the rings back. Prolly gonna add a Netring page at my website :-) with some cool friend's sites

**Comment by maxboeck** [comment]
@LautaroLobo12 awesome 👍

**Comment by kaceo** [comment]
How about:

- webchain

**Comment by amreo** [comment]
webhug

**Comment by peterjaffray** [comment]
webhug

**Comment by tnaia** [comment]
Rings have no beginning...  well, by rotating ring we get grin
(and that's kind of neat, but I couldn't put that to great use...)

- grin
- ringrin

**Comment by cassiterite19** [comment]
I know this is an old topic, but if it helps, the trademark for webring is expiring in two years haha

**Comment by SammoWammo1** [comment]
Netring?????
